BRAZILIAN_STATES = [
    "Acre",
    "Alagoas",
    "Amazonas",
    "Amapa",
    "Bahia",
    "Ceara",
    "Federal District",
    "Espirito Santo",
    "Goias",
    "Maranhao",
    "Minas Gerais",
    "Mato Grosso do Sul",
    "Mato Grosso",
    "Para",
    "Paraiba",
    "Pernambuco",
    "Piaui",
    "Parana",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Roraima",
    "Rondonia",
    "Rio Grande do Sul",
    "Santa Catarina",
    "Sergipe",
    "Sao Paulo",
    "Tocantins",
]
